spring.application.name=12-SpringReST-H2-database

#server configuration
server.port = 9999

#db configuration details

#this one is for in memory db
#spring.datasource.url= jdbc:h2:mem:testDb

#this one is for in prestance db
spring.datasource.url=jdbc:h2:file:D:/H2Db
spring.datasource.username=root
spring.datasource.password=root123

#informing springboot to perform datainitaializaton 
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always